* Security
** Permissions
Because I always forget the bloody order, permission bits are:

|------+-------+---------|
| Read | Write | Execute |
|------+-------+---------|
|    4 |     2 |       1 |
|------+-------+---------|
Order when setting (i.e. =chmod 755 fred=) is /owner/ (user), /group/, /all/.

Mental note to self: group, by default is set to the goup of the person who created it, but can be changed to any group.  A file can be owned by only one group.

If using letters in =chmod=, it's /u, g, o, a/ for user, group, other, all.

** UMASK
My dyscalculia hates this.....


** setuid & setgid &
This allow anyone with execute access to the file, to run it with the same permissions as the file's owner or group.  Use =chmod u+s <name>= and =chmod g+s <name>=.  Note that using setgid on a directory means that any files created in that directory inherit from the goup of that directory.

Note that in the following:
#+begin_src shell
❯ ls -l /usr/bin/sudo
-rwsr-xr-x 1 root root 276K Oct 22 09:58 /usr/bin/sudo
#+end_src
the =s= is lowercase, meaning that the execute bit is also set.  It would be uppercase if it wasn't.

** Sticky bit (applies to directories)
When set, only the owner (user) can delete or rename files in the directory.  Set with =chmod +t <dir_name>=.  It's indicated with a =t= in place of the =x=:

#+begin_src shell
❯ ls -ld /tmp
drwxrwxrwt 15 root root 360 Nov 26 20:33 /tmp/
#+end_src
* UDEV
Note: I'm skipping a few things here, just focusing on what I'm most likely to use.

Used to trigger events for devices under the ~/dev~ directory.

Trigger rules are in ~/lib/udev/rules.d~ (default) and ~/etc/udev/rules.d~ (custom) - ~etc~ takes precedence and rules are processed in lexical order.

Each line that's not a comment, is made up of key/value pairs, with 'match' keys and 'assignment' keys:
 - ~==~ :: Equality.
 - ~!=~ :: Not equal.
 - = :: Assigns a value to a key.
 - ~+=~ :: Add value to key.
 - := :: Assigns a final value to a key, disallowing any further changes by later rules.

** Keys
 * ACTION :: Matches the name of the event action (add, change etc).
 * KERNEL :: Matches the name of the event device.
 * DEVPATH :: Matches the path to the event (under ~/dev~).
 * SUBSYSTEM :: Matches the entire subsystem the device belongs to.
 * DRIVER :: Only set for devices which are bound to a driver when the event is triggered.
 * ENV{key} :: Matches against a device property value.
 * TAG :: Matches against a device tag.
 * PROGRAM :: Matches against the result of a program.
 * RESULT :: Matches against the returned string of ~PROGRAM~

The standard globs can be used, ~*~ (zero of more) ~?~ (any single character), ~[]~ (any single char listed in the brackets), ~|~ alternative

** Assignment
The following keys can be assigned to:
 * NAME
 * SYMLINK
 * OWNER, GROUP, MODE
 * OPTIONS
 * ATTR{key}
 * ENV{key}
 * TAG
 * RUN
 * LABEL :: Sets a label for use with a ~GOTO~.
 * GOTO :: Jumps to the next ~LABEL~ with a matching name.

** String substitution
~NAME, SYMLINK, PROGRAM, OWNER, GROUP, MODE & RUN~ can all use string substitution.  See the ~udev~ man pages for available substitutions.
