* Installation notes
*WARNING* Even if you unselect X11 etc, you'll still be given a /usr/X11R6 partition.

~man afterboot~ is a good place to start once installed.

[[https://ftp.openbsd.org/pub/OpenBSD/doc/obsd-faq.txt][A few years old, but this FAQ is still valid and very useful.]]

** Post installation
Run ~syspatch~ to apply latest patches.

Configure ~doas (doas.conf)~ to allow self to manage services:
#+begin_src shell
permit persist matt as root cmd rcctl
permit persist matt as root cmd pkg_add
permit persist matt as root cmd reboot
#+end_src

Turn off ~sndiod, smtpd~, turn on ~wsmoused~ if you want it.

Kill unwanted TTYs in ~/etc/ttys~
* Services
All done via ~rcctl~:
#+begin_src bash
# list
rcctl ls all|failed|off|on|started|stopped

# start/stop
rcctl -df start|stop|restart|check|reload daemon

# info
rcctl get|getdef|set

# enabling
rcctl enable|disable
#+end_src
This is a front-end for ~/etc/rc.conf~, automatically creating and adding to ~/etc/rc.conf.local~, always leaving the original untouched (so system updates don't effect your changes).
* Networking
[[https://ftp.openbsd.org/pub/OpenBSD/doc/obsd-faq.txt][Part 6 of the FAQ]] - read through it all, try stuff out and take notes.
[[https://www.youtube.com/watch?v=6_FHs_g1yw4&disable_polymer=true][Networking 101]] - watch and take notes.
[[https://www.youtube.com/watch?v=QKfk7YFILws&disable_polymer=true][Long, and probably terminally boring]] - but does have some interesting low-level stuff.

* Filesystem
 - /tmp :: World-writeable, cleared each night and reboot, mounted with ~nodev, nonosuid~.
 - /var :: logs, mail boxes, mail spool, tmp (purged nightly but survives reboots), crash (stores core dumps).
 - /usr :: Most binaries, libraries, docs, man pages.  Basically the core OpenBSD system.
 - /usr/local :: "Locally installed binaries and libs for local applications."
 - /usr/src :: System source, empty by default.
 - usr/obj :: Used for builds.
* Passwords
If, for whatever reason, I need to edit ~/etc/master.passwd~, use the ~vipw~ tool, which will regenerate things that may need regenerating.
* Keymapping
The only one that matters:
#+begin_src bash
wsconsctl keyboard.map+="keysym Caps_Lock = Control_l"
#+end_src
